language: python
dist: xenial
python:
  - 3.7.6
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=nirothegreat/myapi
before_install:
  - python --version
  - pip3 install -U codecov
install:
  - pip3 install -U pytest
before_script:
  - ls -ltr
  - sed -i  -e "s/mysha/${TRAVIS_COMMIT}/" ./myapi/app/static/data/metadata.json
script:
  - pytest
  #- docker build -t nirothegreat/myapi .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
after_success:
  - codecov --file coverage/lcov.info --disable search
